# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/predator/Documents/Project/temp/libtiff

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/predator/Documents/Project/temp/libtiff

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: all
	$(Q)./config/config.sh 1200 "construct"
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named port

# Build rule for target.
port: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 port
.PHONY : port

# fast build rule for target.
port/fast:
	$(MAKE) -f port/CMakeFiles/port.dir/build.make port/CMakeFiles/port.dir/build
.PHONY : port/fast

#=============================================================================
# Target rules for targets named tiff

# Build rule for target.
tiff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tiff
.PHONY : tiff

# fast build rule for target.
tiff/fast:
	$(MAKE) -f libtiff/CMakeFiles/tiff.dir/build.make libtiff/CMakeFiles/tiff.dir/build
.PHONY : tiff/fast

#=============================================================================
# Target rules for targets named tiffxx

# Build rule for target.
tiffxx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tiffxx
.PHONY : tiffxx

# fast build rule for target.
tiffxx/fast:
	$(MAKE) -f libtiff/CMakeFiles/tiffxx.dir/build.make libtiff/CMakeFiles/tiffxx.dir/build
.PHONY : tiffxx/fast

#=============================================================================
# Target rules for targets named tiffsplit

# Build rule for target.
tiffsplit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tiffsplit
.PHONY : tiffsplit

# fast build rule for target.
tiffsplit/fast:
	$(MAKE) -f tools/CMakeFiles/tiffsplit.dir/build.make tools/CMakeFiles/tiffsplit.dir/build
.PHONY : tiffsplit/fast

#=============================================================================
# Target rules for targets named tiff2rgba

# Build rule for target.
tiff2rgba: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tiff2rgba
.PHONY : tiff2rgba

# fast build rule for target.
tiff2rgba/fast:
	$(MAKE) -f tools/CMakeFiles/tiff2rgba.dir/build.make tools/CMakeFiles/tiff2rgba.dir/build
.PHONY : tiff2rgba/fast

#=============================================================================
# Target rules for targets named ppm2tiff

# Build rule for target.
ppm2tiff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ppm2tiff
.PHONY : ppm2tiff

# fast build rule for target.
ppm2tiff/fast:
	$(MAKE) -f tools/CMakeFiles/ppm2tiff.dir/build.make tools/CMakeFiles/ppm2tiff.dir/build
.PHONY : ppm2tiff/fast

#=============================================================================
# Target rules for targets named tiff2ps

# Build rule for target.
tiff2ps: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tiff2ps
.PHONY : tiff2ps

# fast build rule for target.
tiff2ps/fast:
	$(MAKE) -f tools/CMakeFiles/tiff2ps.dir/build.make tools/CMakeFiles/tiff2ps.dir/build
.PHONY : tiff2ps/fast

#=============================================================================
# Target rules for targets named tiffcp

# Build rule for target.
tiffcp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tiffcp
.PHONY : tiffcp

# fast build rule for target.
tiffcp/fast:
	$(MAKE) -f tools/CMakeFiles/tiffcp.dir/build.make tools/CMakeFiles/tiffcp.dir/build
.PHONY : tiffcp/fast

#=============================================================================
# Target rules for targets named tiffdither

# Build rule for target.
tiffdither: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tiffdither
.PHONY : tiffdither

# fast build rule for target.
tiffdither/fast:
	$(MAKE) -f tools/CMakeFiles/tiffdither.dir/build.make tools/CMakeFiles/tiffdither.dir/build
.PHONY : tiffdither/fast

#=============================================================================
# Target rules for targets named tiffinfo

# Build rule for target.
tiffinfo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tiffinfo
.PHONY : tiffinfo

# fast build rule for target.
tiffinfo/fast:
	$(MAKE) -f tools/CMakeFiles/tiffinfo.dir/build.make tools/CMakeFiles/tiffinfo.dir/build
.PHONY : tiffinfo/fast

#=============================================================================
# Target rules for targets named pal2rgb

# Build rule for target.
pal2rgb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pal2rgb
.PHONY : pal2rgb

# fast build rule for target.
pal2rgb/fast:
	$(MAKE) -f tools/CMakeFiles/pal2rgb.dir/build.make tools/CMakeFiles/pal2rgb.dir/build
.PHONY : pal2rgb/fast

#=============================================================================
# Target rules for targets named ras2tiff

# Build rule for target.
ras2tiff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ras2tiff
.PHONY : ras2tiff

# fast build rule for target.
ras2tiff/fast:
	$(MAKE) -f tools/CMakeFiles/ras2tiff.dir/build.make tools/CMakeFiles/ras2tiff.dir/build
.PHONY : ras2tiff/fast

#=============================================================================
# Target rules for targets named rgb2ycbcr

# Build rule for target.
rgb2ycbcr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rgb2ycbcr
.PHONY : rgb2ycbcr

# fast build rule for target.
rgb2ycbcr/fast:
	$(MAKE) -f tools/CMakeFiles/rgb2ycbcr.dir/build.make tools/CMakeFiles/rgb2ycbcr.dir/build
.PHONY : rgb2ycbcr/fast

#=============================================================================
# Target rules for targets named tiff2bw

# Build rule for target.
tiff2bw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tiff2bw
.PHONY : tiff2bw

# fast build rule for target.
tiff2bw/fast:
	$(MAKE) -f tools/CMakeFiles/tiff2bw.dir/build.make tools/CMakeFiles/tiff2bw.dir/build
.PHONY : tiff2bw/fast

#=============================================================================
# Target rules for targets named raw2tiff

# Build rule for target.
raw2tiff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 raw2tiff
.PHONY : raw2tiff

# fast build rule for target.
raw2tiff/fast:
	$(MAKE) -f tools/CMakeFiles/raw2tiff.dir/build.make tools/CMakeFiles/raw2tiff.dir/build
.PHONY : raw2tiff/fast

#=============================================================================
# Target rules for targets named thumbnail

# Build rule for target.
thumbnail: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 thumbnail
.PHONY : thumbnail

# fast build rule for target.
thumbnail/fast:
	$(MAKE) -f tools/CMakeFiles/thumbnail.dir/build.make tools/CMakeFiles/thumbnail.dir/build
.PHONY : thumbnail/fast

#=============================================================================
# Target rules for targets named bmp2tiff

# Build rule for target.
bmp2tiff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bmp2tiff
.PHONY : bmp2tiff

# fast build rule for target.
bmp2tiff/fast:
	$(MAKE) -f tools/CMakeFiles/bmp2tiff.dir/build.make tools/CMakeFiles/bmp2tiff.dir/build
.PHONY : bmp2tiff/fast

#=============================================================================
# Target rules for targets named fax2ps

# Build rule for target.
fax2ps: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fax2ps
.PHONY : fax2ps

# fast build rule for target.
fax2ps/fast:
	$(MAKE) -f tools/CMakeFiles/fax2ps.dir/build.make tools/CMakeFiles/fax2ps.dir/build
.PHONY : fax2ps/fast

#=============================================================================
# Target rules for targets named fax2tiff

# Build rule for target.
fax2tiff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fax2tiff
.PHONY : fax2tiff

# fast build rule for target.
fax2tiff/fast:
	$(MAKE) -f tools/CMakeFiles/fax2tiff.dir/build.make tools/CMakeFiles/fax2tiff.dir/build
.PHONY : fax2tiff/fast

#=============================================================================
# Target rules for targets named tiffcmp

# Build rule for target.
tiffcmp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tiffcmp
.PHONY : tiffcmp

# fast build rule for target.
tiffcmp/fast:
	$(MAKE) -f tools/CMakeFiles/tiffcmp.dir/build.make tools/CMakeFiles/tiffcmp.dir/build
.PHONY : tiffcmp/fast

#=============================================================================
# Target rules for targets named gif2tiff

# Build rule for target.
gif2tiff: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gif2tiff
.PHONY : gif2tiff

# fast build rule for target.
gif2tiff/fast:
	$(MAKE) -f tools/CMakeFiles/gif2tiff.dir/build.make tools/CMakeFiles/gif2tiff.dir/build
.PHONY : gif2tiff/fast

#=============================================================================
# Target rules for targets named tiffset

# Build rule for target.
tiffset: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tiffset
.PHONY : tiffset

# fast build rule for target.
tiffset/fast:
	$(MAKE) -f tools/CMakeFiles/tiffset.dir/build.make tools/CMakeFiles/tiffset.dir/build
.PHONY : tiffset/fast

#=============================================================================
# Target rules for targets named tiff2pdf

# Build rule for target.
tiff2pdf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tiff2pdf
.PHONY : tiff2pdf

# fast build rule for target.
tiff2pdf/fast:
	$(MAKE) -f tools/CMakeFiles/tiff2pdf.dir/build.make tools/CMakeFiles/tiff2pdf.dir/build
.PHONY : tiff2pdf/fast

#=============================================================================
# Target rules for targets named tiffcrop

# Build rule for target.
tiffcrop: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tiffcrop
.PHONY : tiffcrop

# fast build rule for target.
tiffcrop/fast:
	$(MAKE) -f tools/CMakeFiles/tiffcrop.dir/build.make tools/CMakeFiles/tiffcrop.dir/build
.PHONY : tiffcrop/fast

#=============================================================================
# Target rules for targets named tiffdump

# Build rule for target.
tiffdump: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tiffdump
.PHONY : tiffdump

# fast build rule for target.
tiffdump/fast:
	$(MAKE) -f tools/CMakeFiles/tiffdump.dir/build.make tools/CMakeFiles/tiffdump.dir/build
.PHONY : tiffdump/fast

#=============================================================================
# Target rules for targets named tiffmedian

# Build rule for target.
tiffmedian: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tiffmedian
.PHONY : tiffmedian

# fast build rule for target.
tiffmedian/fast:
	$(MAKE) -f tools/CMakeFiles/tiffmedian.dir/build.make tools/CMakeFiles/tiffmedian.dir/build
.PHONY : tiffmedian/fast

#=============================================================================
# Target rules for targets named strip_rw

# Build rule for target.
strip_rw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 strip_rw
.PHONY : strip_rw

# fast build rule for target.
strip_rw/fast:
	$(MAKE) -f test/CMakeFiles/strip_rw.dir/build.make test/CMakeFiles/strip_rw.dir/build
.PHONY : strip_rw/fast

#=============================================================================
# Target rules for targets named rewrite

# Build rule for target.
rewrite: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rewrite
.PHONY : rewrite

# fast build rule for target.
rewrite/fast:
	$(MAKE) -f test/CMakeFiles/rewrite.dir/build.make test/CMakeFiles/rewrite.dir/build
.PHONY : rewrite/fast

#=============================================================================
# Target rules for targets named ascii_tag

# Build rule for target.
ascii_tag: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ascii_tag
.PHONY : ascii_tag

# fast build rule for target.
ascii_tag/fast:
	$(MAKE) -f test/CMakeFiles/ascii_tag.dir/build.make test/CMakeFiles/ascii_tag.dir/build
.PHONY : ascii_tag/fast

#=============================================================================
# Target rules for targets named long_tag

# Build rule for target.
long_tag: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 long_tag
.PHONY : long_tag

# fast build rule for target.
long_tag/fast:
	$(MAKE) -f test/CMakeFiles/long_tag.dir/build.make test/CMakeFiles/long_tag.dir/build
.PHONY : long_tag/fast

#=============================================================================
# Target rules for targets named custom_dir

# Build rule for target.
custom_dir: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 custom_dir
.PHONY : custom_dir

# fast build rule for target.
custom_dir/fast:
	$(MAKE) -f test/CMakeFiles/custom_dir.dir/build.make test/CMakeFiles/custom_dir.dir/build
.PHONY : custom_dir/fast

#=============================================================================
# Target rules for targets named raw_decode

# Build rule for target.
raw_decode: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 raw_decode
.PHONY : raw_decode

# fast build rule for target.
raw_decode/fast:
	$(MAKE) -f test/CMakeFiles/raw_decode.dir/build.make test/CMakeFiles/raw_decode.dir/build
.PHONY : raw_decode/fast

#=============================================================================
# Target rules for targets named short_tag

# Build rule for target.
short_tag: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 short_tag
.PHONY : short_tag

# fast build rule for target.
short_tag/fast:
	$(MAKE) -f test/CMakeFiles/short_tag.dir/build.make test/CMakeFiles/short_tag.dir/build
.PHONY : short_tag/fast

#=============================================================================
# Target rules for targets named addtiffo

# Build rule for target.
addtiffo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 addtiffo
.PHONY : addtiffo

# fast build rule for target.
addtiffo/fast:
	$(MAKE) -f contrib/addtiffo/CMakeFiles/addtiffo.dir/build.make contrib/addtiffo/CMakeFiles/addtiffo.dir/build
.PHONY : addtiffo/fast

#=============================================================================
# Target rules for targets named tiff-rgb

# Build rule for target.
tiff-rgb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tiff-rgb
.PHONY : tiff-rgb

# fast build rule for target.
tiff-rgb/fast:
	$(MAKE) -f contrib/dbs/CMakeFiles/tiff-rgb.dir/build.make contrib/dbs/CMakeFiles/tiff-rgb.dir/build
.PHONY : tiff-rgb/fast

#=============================================================================
# Target rules for targets named tiff-palette

# Build rule for target.
tiff-palette: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tiff-palette
.PHONY : tiff-palette

# fast build rule for target.
tiff-palette/fast:
	$(MAKE) -f contrib/dbs/CMakeFiles/tiff-palette.dir/build.make contrib/dbs/CMakeFiles/tiff-palette.dir/build
.PHONY : tiff-palette/fast

#=============================================================================
# Target rules for targets named tiff-grayscale

# Build rule for target.
tiff-grayscale: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tiff-grayscale
.PHONY : tiff-grayscale

# fast build rule for target.
tiff-grayscale/fast:
	$(MAKE) -f contrib/dbs/CMakeFiles/tiff-grayscale.dir/build.make contrib/dbs/CMakeFiles/tiff-grayscale.dir/build
.PHONY : tiff-grayscale/fast

#=============================================================================
# Target rules for targets named tiff-bi

# Build rule for target.
tiff-bi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tiff-bi
.PHONY : tiff-bi

# fast build rule for target.
tiff-bi/fast:
	$(MAKE) -f contrib/dbs/CMakeFiles/tiff-bi.dir/build.make contrib/dbs/CMakeFiles/tiff-bi.dir/build
.PHONY : tiff-bi/fast

#=============================================================================
# Target rules for targets named iptcutil

# Build rule for target.
iptcutil: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iptcutil
.PHONY : iptcutil

# fast build rule for target.
iptcutil/fast:
	$(MAKE) -f contrib/iptcutil/CMakeFiles/iptcutil.dir/build.make contrib/iptcutil/CMakeFiles/iptcutil.dir/build
.PHONY : iptcutil/fast

#=============================================================================
# Target rules for targets named htmldoc

# Build rule for target.
htmldoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 htmldoc
.PHONY : htmldoc

# fast build rule for target.
htmldoc/fast:
	$(MAKE) -f html/man/CMakeFiles/htmldoc.dir/build.make html/man/CMakeFiles/htmldoc.dir/build
.PHONY : htmldoc/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... rebuild_cache"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... test"
	@echo "... edit_cache"
	@echo "... port"
	@echo "... tiff"
	@echo "... tiffxx"
	@echo "... tiffsplit"
	@echo "... tiff2rgba"
	@echo "... ppm2tiff"
	@echo "... tiff2ps"
	@echo "... tiffcp"
	@echo "... tiffdither"
	@echo "... tiffinfo"
	@echo "... pal2rgb"
	@echo "... ras2tiff"
	@echo "... rgb2ycbcr"
	@echo "... tiff2bw"
	@echo "... raw2tiff"
	@echo "... thumbnail"
	@echo "... bmp2tiff"
	@echo "... fax2ps"
	@echo "... fax2tiff"
	@echo "... tiffcmp"
	@echo "... gif2tiff"
	@echo "... tiffset"
	@echo "... tiff2pdf"
	@echo "... tiffcrop"
	@echo "... tiffdump"
	@echo "... tiffmedian"
	@echo "... strip_rw"
	@echo "... rewrite"
	@echo "... ascii_tag"
	@echo "... long_tag"
	@echo "... custom_dir"
	@echo "... raw_decode"
	@echo "... short_tag"
	@echo "... addtiffo"
	@echo "... tiff-rgb"
	@echo "... tiff-palette"
	@echo "... tiff-grayscale"
	@echo "... tiff-bi"
	@echo "... iptcutil"
	@echo "... htmldoc"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

